### ISSUE TITLE
any possibility to show computed field result?

### ISSUE THREAD

**Issue by lucieperrie** [drupal-fancy/inline_entity_form_preview#4]
I am looking for a way to display a computed field result in the inline entity form table. I was hoping this module might help me, but in the displayed preview the computed field results are blank. Is there any tweak possible that might help? In a normal preview the computed fields display just fine.

**Comment by yannickoo** [comment]
Sounds interesting, I will take a look on that this week :)

**Comment by lucieperrie** [comment]
thank you!

**Comment by lucieperrie** [comment]
Hi, actually I was able to solve this without any changes to the IEF Preview module. I made some small patches to the computed field module and to the IEF module.

**Comment by yannickoo** [comment]
That sounds great! Could you please link those patches? :)

**Comment by lucieperrie** [comment]
Here is the link to the thread on drupal.org where I described the changes I made:
https://www.drupal.org/node/2377341

I will try to post patches soon. (Still learning how to roll/apply patches!)
